### ISSUE TITLE
How can I create PR for docs

### ISSUE THREAD

**Issue by Bafff** [Chia-Network/chia-docs#1]
Hi!

I just want to share my small modifications into chia-blockchain Wiki https://github.com/Chia-Network/chia-blockchain.wiki.git for https://github.com/Chia-Network/chia-blockchain/wiki/Chia-Keys-Management#2-keys-farming-key--cold-storage-key article but I do not understand how this is possible?

Your help is much appreciated

**Comment by danieljperry** [comment]
This is the wrong repo. Go to "https://github.com/Chia-Network/", create a new branch with your suggested changes, and do a pull request.
