### ISSUE TITLE
Github edit links missing /blob/

### ISSUE THREAD

**Issue by hoffmang9** [Chia-Network/chia-docs#23]
On this page: https://docs.chia.net/docs/03consensus/consensus_intro
![image](https://user-images.githubusercontent.com/30377676/147979870-f2044e06-b1ee-4be7-a8cc-d8a19ca6dbbe.png)

When one clicks the Edit button, the resulting URL is missing `/blob/`.

`https://github.com/Chia-Network/chia-docs/docs/03consensus/consensus_intro.md` should be `https://github.com/Chia-Network/chia-docs/blob/main/docs/03consensus/consensus_intro.md`

**Comment by wizicer** [comment]
How about redirecting to `https://github.com/Chia-Network/chia-docs/edit/main/docs/03consensus/consensus_intro.md` this page instead, which is a truly `Edit`.
