### ISSUE TITLE
cat creation tutorial cdv not install w/ cat admin tool

### ISSUE THREAD

**Issue by AdrianScott** [Chia-Network/chia-docs#238]
https://github.com/Chia-Network/chia-docs/blob/main/docs/guides/cat/cat-creation-tutorial.md

https://docs.chia.net/guides/cat-creation-tutorial

following the instructions (linux/ubuntu),
i already have chia 1.3+ installed, so i skip to cat-admin-tool installation
and follow those instructions

cats -- help 
works

but 
cdv --help 
doesn't work (Command 'cdv' not found, did you mean...)

I don't see anything in the instructions/files that should have installed cdv

**Comment by BrandtH22** [comment]
Resolved in https://github.com/Chia-Network/chia-docs/pull/399
