### ISSUE TITLE
https://docs.chia.net/wallet-rpc/#get_wallets - not a valid wallet type

### ISSUE THREAD

**Issue by forReason** [Chia-Network/chia-docs#323]
according to https://docs.chia.net/wallet-rpc/#get_wallets 

> The type of wallet to retrieve. If included, must be one of `cat_wallet`, `did_wallet`, `nft_wallet`, or `pool_wallet`
```
{
    "error": "'cat_wallet' is not a valid WalletType", 
    "success": false
}
```

I ve also tried with the numeric value but:
```
"'6' is not a valid WalletType"
```

**Comment by danieljperry** [comment]
String wallet types don't work for that RPC. Sorry about that. However, integers such as `6` should work. I will update the documentation. Meanwhile, you can find the valid wallet types here:
https://github.com/Chia-Network/chia-blockchain/blob/main/chia/wallet/util/wallet_types.py

**Comment by danieljperry** [comment]
For example, this command will return CAT wallets:
`chia rpc wallet get_wallets '{"type": 6}'`
