### ISSUE TITLE
What are TransactionType's?

### ISSUE THREAD

**Issue by KryptomineCH** [Chia-Network/chia-docs#358]
Hi there,

I am looking for a documentation of the enum `TransactionType` for the Chia Client Api

Unfortunately, the TransactionRecord has a link in the official Documentation but the link leads nowhere:
https://docs.chia.net/walletconnect-commands#transactiontype

----------

Im looking for something simmilar to:
https://docs.chia.net/walletconnect-commands/#wallettype

**Comment by danieljperry** [comment]
Thanks, we'll work on this documentation soon.

**Comment by forReason** [comment]
found out a little more:
```
0 - Incoming
1 - Outgoing
2 - CoinbaseReward
3 - FeeReward
4 - IncomingTrade
5 - OutgoingTrade
```

follow up question?

what defines a trade? Is that an offer fullfillment?

**Comment by KryptomineCH** [comment]
Trades Are Offer Related
