### ISSUE TITLE
RPC - `sort_keys` documentation inconsistencies und clarifications

### ISSUE THREAD

**Issue by KryptomineCH** [Chia-Network/chia-docs#419]
Several Endpoints such as [get_all_offers](https://docs.chia.net/offer-rpc?_highlight=get_all_offers#get_all_offers) have a property `sort_key`

What is the default `sort_key` and how do I know which sort keys are available/refer to which properties?

At the time I'm particularly interested for the endpoints `get_all_offers` and  `get_transactions`

---------------
Notably the documentation on `get_all_offers` shows its of type string. The documentation on `get_transactions` shows its of type number

--------------
I tried to test a little and it seems either the sort key is not implemented or it is not trivial. Or the type is not long/int:
```json
{{
  "offers": null,
  "trade_records": null,
  "success": false,
  "error": "No known sort 0"
}}
```

string is not trivial either:
```c#
GetAllOffers_RPC getAllOffers_RPC = new GetAllOffers_RPC(
    start: heightInfo.ImportedOfferHeight.SequenceHeight,
    end: long.MaxValue,
    exclude_my_offers: false,
    exclude_taken_offers: false,
    include_completed: true,
    sort_key: null,//"created_at_time",
    reverse: true,
    file_contents: true) ;
```
```json
{{
  "offers": null,
  "trade_records": null,
  "success": false,
  "error": "No known sort created_at_time"
}}
```

**Comment by BrandtH22** [comment]
Hey @KryptomineCH , I am sorry for the delayed response. 

Upon review it looks like the get_all_offers endpoint accepts either `confirmed_at_height` or `relevance` with `confirmed_at_height` being the default:
https://github.com/Chia-Network/chia-blockchain/blob/5f6c336e757534d3a36b1a03612e05b412a18c61/chia/wallet/trading/trade_store.py#L413

In addition it looks like the get_transactions endpoint also accepts `confirmed_at_height` or `relevance` with `confirmed_at_height` being the default:
https://github.com/Chia-Network/chia-blockchain/blob/5f6c336e757534d3a36b1a03612e05b412a18c61/chia/wallet/wallet_transaction_store.py#L311

sort key members: https://github.com/Chia-Network/chia-blockchain/blob/5f6c336e757534d3a36b1a03612e05b412a18c61/chia/wallet/transaction_sorting.py#L6
