### ISSUE TITLE
`trade_record` status clarification requested

### ISSUE THREAD

**Issue by KryptomineCH** [Chia-Network/chia-docs#420]
I would like to request some documentation improvements or alternatively explanations on `trade_record` of an offer File.

I am trying to make sense of the following `trade_record`:
![image](https://github.com/Chia-Network/chia-docs/assets/117320700/7ad11681-d6e7-4749-bea6-d54df6e200fd)

```c#
- accepted_at_time = null // indicates to me the offer has not been accepted
- confirmed_at_index = 0 // indicates to me the offer has not been accepted
- pending = 1 // seems to be only half of the offer. Cant really make sense of that`- awaiting accept?
- sent_to = 0 // probably empty because I created the offer??
- status = CONFIRMED // indicates to me that the offer was accepted
```

Is it `confirmed (executed)`, `pending (awaiting accept)`, `pending (awaiting transaction)`, or `nothing at all (since not sent to blockchain)` ??

**Comment by BrandtH22** [comment]
Hey @KryptomineCH , yes it seems you have interpreted all of this correctly. I believe the sent_to might be related to sending onchain notifications for offer files (currently tied to having an NFT included in the offer file and the notification is sent to the xch address that owns the nft). 

Were there any other questions regarding this? (note I am also working on the other transaction issue reported and making sure your excellent notes are added to the docs site)
