### ISSUE TITLE
docs say genesis but should be agg sig me additional data

### ISSUE THREAD

**Issue by Abachrombie** [Chia-Network/chia-docs#466]
code/docs are wrong

they happen to be the same for mainnet, but not for other nets like simulator/testnet

https://docs.chia.net/guides/crash-course/state/

ref
https://twitter.com/Rigidity16/status/1743284597297651856

**Comment by Rigidity** [comment]
On testnet10 I think they are actually the same, but yeah simulator0 has its own genesis challenge (I presume a new one is created every time since you're creating a new chain). The simulator uses mainnet's genesis challenge as its `AGG_SIG_ME_ADDITIONAL_DATA`.
