### ISSUE TITLE
learn chialisp playlist out of order

### ISSUE THREAD

**Issue by Anarkoic** [Chia-Network/chia-docs#704]
the learn chialisp playlist on Youtube in the Chia channel is in the wrong order i think; i think #4 should be second;
https://www.youtube.com/playlist?list=PLmnzWPUjpmaFNHw_W0oi7KQbuKl8Sq0tr

**Comment by BrandtH22** [comment]
Hey @Anarkoic , thank you for the heads up this should now be updated to be in the proper order to follow the chia academy lessons:
https://docs.chia.net/academy/chialisp/
