### ISSUE TITLE
Fix explanation on minimum fees

### ISSUE THREAD

**Issue by mariano54** [Chia-Network/chia-docs#75]
This was a misunderstanding on my part, let me explain how it works. I think the way it works now is fine. There are two cases:

Case 1: The mempool is full. In this case, let's assume the mempool is full of 0 fee TX, you need a minimum fee (5 fee per cost) to kick out a transaction from the mempool. If you use a 1 mojo fee, your transaction will get rejected.
Case 2: The mempool is not full. Then your transaction (and any transaction) can get added to the mempool. The ordering of inclusion is always determined by fee / cost, so a 1 mojo greater TX will get in first.

Therefore, you cannot kick out other transactions by increasing the fee slightly, which prevents attacks. But you can get some priority. The mempool is not currently full, but it was at some point in the past with other dust storms, so this strategy is not guaranteed to always work.

Also, the fee required to replace your own transaction MUST be >= the minimum 5 fee per cost. Respending your own TX with a 1 mojo fee will not lead to re-propagation and therefore will not work.

**Comment by hoffmang9** [comment]
I believe this is fixed?
