### ISSUE TITLE
Bug in synthetic offset description.

### ISSUE THREAD

**Issue by cameroncooper** [Chia-Network/chia-docs#85]
The formula for `synthetic_offset` in the docs (https://chialisp.com/docs/standard_transaction/) is incorrect.

The docs say it is `synthetic_offset == sha256(hidden_puzzle_hash + original_public_key)`

But the code has it as `hashlib.sha256(bytes(public_key) + hidden_puzzle_hash).digest()`

So the docs should have the parameters swapped: `synthetic_offset == sha256(original_public_key + hidden_puzzle_hash)`

Thanks Freddie for finding this one.

**Comment by Rigidity** [comment]
Fixed
