### ISSUE TITLE
Document get_connections and remaining shared RPC methods

### ISSUE THREAD

**Issue by mariano54** [Chia-Network/chia-docs#86]

**Comment by danieljperry** [comment]
A lot of this work has been done external to Chia. It's a matter of integrating this work into docs.chia.net. Here's the repo:
https://github.com/dkackman/chia-api

Specifically for get_connections:
https://dkackman.github.io/chia-api/static/fullnode.html#api-Connections-getConnections

**Comment by BrandtH22** [comment]
protocols all have the necessary links from #559 , detailed information will not be documented on these per request from product
